name: Project Pipeline

on:
  push:
    paths:
      - "project/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install sqlalchemy pandas numpy lxml
          # pip3 install lxml

      - name: Run pipeline.py
        run: python project/pipeline.py

      - name: Run test.py
        run: python project/test.py
